[project]
name = "kabu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>5,<6",
    "django-countries>=7.6.1",
    "environs>=14.1.1",
    "uwsgi>=2.0.29",
]
