# Generated by Django 5.2 on 2025-04-20 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("players", "0001_initial"),
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("point_version", models.CharField(default="v1")),
            ],
        ),
        migrations.CreateModel(
            name="Standing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Participation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("swiss_win", models.PositiveIntegerField()),
                ("final_standing", models.PositiveIntegerField()),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="players.player",
                    ),
                ),
                (
                    "standing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tournaments.standing",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("date", models.DateField(auto_now=True)),
                ("description", models.TextField(blank=True)),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tournaments.season",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="shops.shop",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="standing",
            name="tournament",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                to="tournaments.tournament",
            ),
        ),
        migrations.AddConstraint(
            model_name="tournament",
            constraint=models.UniqueConstraint(
                fields=("number", "season", "shop"),
                name="only_one_number_by_shop_by_season",
            ),
        ),
    ]
