# Generated by Django 5.2 on 2025-04-21 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="participation",
            options={"ordering": ["final_standing"]},
        ),
        migrations.AlterField(
            model_name="tournament",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
