# Generated by Django 5.2 on 2025-05-04 21:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0003_matchresult"),
    ]

    operations = [
        migrations.RenameField(
            model_name="matchresult",
            old_name="looser",
            new_name="loser",
        ),
    ]
