# Generated by Django 5.2 on 2025-04-20 21:18

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("address", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("country", django_countries.fields.CountryField(max_length=2)),
            ],
        ),
    ]
